/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package  Cloud.ui;
import Cloud.fc.ConnexionBD;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Juliette-Trouillet
 */
public class ConnexionSIR extends javax.swing.JFrame {

    /**
     * Creates new form ConnexionSIR
     */
    public ConnexionSIR() {
        initComponents();
        setResizable(false);
        jLabel4.setSize(1500,700);
        setSize(1500,700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Identifiant : ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(850, 90, 230, 30);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mot de passe : ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(800, 200, 290, 50);

        jTextField1.setText("                                   ");
        jTextField1.setToolTipText("");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(1110, 90, 270, 40);

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(1110, 210, 270, 40);

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton1.setText("Connexion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) { // Léo: try/catch ajouté pour la gestion de Exception
                try{jButton1ActionPerformed(evt);}
                catch(Exception e){};
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(1230, 330, 140, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cloud/image/LoginFrame-2.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, -10, 1780, 720);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1700, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws Exception {
        ConnexionBD con = new ConnexionBD();
        ArrayList<ArrayList<String>> listeIdentifiants = new ArrayList<>();
        String id = jTextField1.getText();
        String password = jPasswordField1.getText();
        con.connexion();
        listeIdentifiants = con.requete("typepersonnel","personnel","where idpersonnel="+"'"+id+"' and mdp="+"'"+password+"' ;");

        if(listeIdentifiants.get(0).get(0)=="PH"){
            PH ph = new PH();
            ph.setVisible(true);
            this.dispose();
        }

        if(listeIdentifiants.get(0).get(0)=="manip"){
            ManipRadio manipR= new ManipRadio();
            manipR.setVisible(true);
            this.dispose();
        }

        if(listeIdentifiants.get(0).get(0)=="secretaire"){
            SecretaireMedicale secmed = new SecretaireMedicale();
            secmed.setVisible(true);
            this.dispose();
        }
        else {
            JOptionPane.showMessageDialog(this, "Identifiant ou Mot de passe inconnu");
        }




//GEN-FIRST:event_jButton1ActionPerformed
//BASE DE DONNEE 
//        if(PH){
//              PH ph = new PH();
//              ph.setVisible(true);
//              this.dispose();
//        }
//        if(ManipRadio){
//            ManipRadio manipR= new ManipRadio();
//            manipR.setVisible(true);
//            this.dispose();
//        }
//        if(SM){
//            SecretaireMed secmed = new SecretaireMed();
//            secmed.setVisible(true);
//            this.dispose();
//        }
    }//GEN-LAST:event_jButton1ActionPerformed




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConnexionSIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConnexionSIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConnexionSIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConnexionSIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConnexionSIR().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
