/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cloud.ui;

import Cloud.fc.ConnexionBD;
import Cloud.fc.*;
import Cloud.fc.random;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Juliette-Trouillet
 */
public class SecretaireMedicale extends javax.swing.JFrame {

    private ArrayList<Examen> listeExamen = new ArrayList<>();
    private ArrayList<Patient> listePatient = new ArrayList<>();

    /**
     * Creates new form SecretaireMedicale
     */
    public SecretaireMedicale() throws SQLException, Exception {
        initComponents();

        setResizable(false);
        jLabel1.setSize(1500, 700);
        jLabel7.setSize(1500, 700);
        jLabel10.setSize(1500, 700);
        setSize(1500, 700);
        jTextField3.setText("");

        //on recolte toutes les info sur le patient pour creer notre liste patient et notre liste examen
        ListeExamenBD listeE = new ListeExamenBD();
        listeExamen = listeE.getListeExamen();
        ListePatientBD listeP = new ListePatientBD(listeExamen);
        listePatient = listeP.getListePatient();

    }

    public SecretaireMedicale(String nom, String prenom) throws Exception {
        initComponents();
        setResizable(false);
        jLabel1.setSize(1500, 700);
        jLabel7.setSize(1500, 700);
        jLabel10.setSize(1500, 700);
        setSize(1500, 700);
        jLabel8.setText(nom);
        jLabel9.setText(prenom);
        jTextField3.setText("");

        //on recolte toutes les info sur le patient pour creer notre liste patient et notre liste examen
        ListeExamenBD listeE = new ListeExamenBD();
        listeExamen = listeE.getListeExamen();
        ListePatientBD listeP = new ListePatientBD(listeExamen);
        listePatient = listeP.getListePatient();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jComboBox2 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel2.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cloud/image/paramètre .png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(80, 570, 50, 50);

        jButton2.setText("Déconnexion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(1000, 570, 150, 40);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nom");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(90, 90, 160, 40);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Prénom");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(90, 240, 220, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cloud/image/wallpaperFinal-4.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1570, 710);

        jTabbedPane1.addTab("Accueil", jPanel2);

        jPanel1.setLayout(null);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Patien 1", "Patient 2", "Patient 3", "Patient 4", "Patient 5", "Patient 6", "Patient 7", "Patien 1", "Patient 2", "Patient 3", "Patient 4", "Patient 5", "Patient 6", "Patient 7", "Patien 1", "Patient 2", "Patient 3", "Patient 4", "Patient 5", "Patient 6", "Patient 7", "Patien 1", "Patient 2", "Patient 3", "Patient 4", "Patient 5", "Patient 6", "Patient 7" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jList1ComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 130, 770, 450);

        jComboBox2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Trier par...", "Médecin", "Patient", "date" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(100, 90, 130, 25);

        jButton4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton4.setText("Trier");
        jPanel1.add(jButton4);
        jButton4.setBounds(270, 90, 63, 27);

        jTextField4.setText("Rechercher...");
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(520, 90, 144, 22);

        jButton5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton5.setText("OK");
        jPanel1.add(jButton5);
        jButton5.setBounds(710, 90, 53, 27);

        jButton6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton6.setText("Exporter en PDF");
        jPanel1.add(jButton6);
        jButton6.setBounds(800, 610, 150, 40);

        jButton7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton7.setText("Imprimer");
        jPanel1.add(jButton7);
        jButton7.setBounds(950, 610, 110, 40);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Selectionnez un patient...");
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(910, 130, 430, 450);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cloud/image/wallpaperFinal-4.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 1730, 830);

        jTabbedPane1.addTab("Exporter un DMR", jPanel1);

        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nom : ");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(310, 70, 90, 32);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Prénom : ");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(280, 170, 130, 32);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date de Naissance : ");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(150, 260, 260, 32);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Identifiant : ");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(240, 350, 170, 32);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("adresse: ");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(260, 450, 110, 32);

        jComboBox1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Femme", "Homme" }));
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(430, 530, 150, 27);

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jPanel3.add(jTextField1);
        jTextField1.setBounds(440, 70, 250, 22);

        jTextField2.setToolTipText("");
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jPanel3.add(jTextField2);
        jTextField2.setBounds(440, 170, 250, 22);

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextField1.setText("jj/mm/aaaa");
        jFormattedTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFormattedTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField1MouseClicked(evt);
            }
        });
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jFormattedTextField1);
        jFormattedTextField1.setBounds(440, 260, 250, 22);

        jTextField3.setEditable(false);
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField3);
        jTextField3.setBounds(440, 360, 250, 22);

        jButton3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton3.setText("Ajouter ce patient");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(1090, 580, 180, 50);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Sexe : ");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(300, 530, 90, 32);

        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField5);
        jTextField5.setBounds(440, 450, 250, 22);

        jButton8.setText("Générer un id");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jPanel3.add(jButton8);
        jButton8.setBounds(730, 360, 120, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cloud/image/wallpaperFinal-4.png"))); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 0, 1730, 830);

        jTabbedPane1.addTab("Ajouter un patient", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1502, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ConnexionSIR decoSM = new ConnexionSIR();
        decoSM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        jTextField4.setText("");
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jFormattedTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField1MouseClicked
        jFormattedTextField1.selectAll();
    }//GEN-LAST:event_jFormattedTextField1MouseClicked

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        jTextField3.setText("");
    }//GEN-LAST:event_jTextField3MouseClicked

    private void jList1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jList1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1ComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ChangerMdp change = new ChangerMdp();
        change.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        if (jTextField3.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Veuillez générer l'identifiant du patient", "Erreur", JOptionPane.WARNING_MESSAGE);
        } else if (jFormattedTextField1.getText().equals("jj/mm/aaaa")) {  //on regarde si l'utilisateur à bien completé la date
            JOptionPane.showMessageDialog(this, "Veuillez compléter la date de naissance", "Erreur", JOptionPane.WARNING_MESSAGE);
        } else {
            String nom = this.jTextField1.getText();
            String prenom = this.jTextField2.getText();
            Date2 date = new Date2(jFormattedTextField1.getText());
            String id = this.jTextField3.getText();
            String adresse = this.jTextField5.getText();
            ArrayList<ArrayList<String>> listeIddb = new ArrayList<>();
            ArrayList<ArrayList<String>> liste = new ArrayList<>();
            random r = new random();
            String iddbpatient;
            ConnexionBD co = new ConnexionBD();
            int sexe = this.jComboBox1.getSelectedIndex();

            try {
                co.connexion();
            } catch (Exception ex) {
                Logger.getLogger(SecretaireMedicale.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                listeIddb = co.requete("iddbpatient", "patient", "");

            } catch (SQLException ex) {
                Logger.getLogger(SecretaireMedicale.class.getName()).log(Level.SEVERE, null, ex);
            }
            iddbpatient = r.genererId(9);  //generer un id pour la database
            while (listeIddb.get(0).contains(iddbpatient)) {  //sert à eviter les doublons d'id dans la base de donnée.
                iddbpatient = r.genererId(9);
            }
            String attribut = "'" + iddbpatient + "'" + "," + "'" + date.toStringDateNaissDB() + "'" + "," + "'" + nom + "'" + "," + "'" + prenom + "'" + "," + "'" + sexe + "'" + "," + "'" + id + "'" + "," + "'" + adresse + "'";
            System.out.println(attribut);
            int i = co.insert("patient", "iddbpatient,datenaissance,nom,prenom,sexe,idpatient,adresse", "'" + iddbpatient + "'" + "," + "'" + date.toStringDateNaissDB() + "'" + "," + "'" + nom + "'" + "," + "'" + prenom + "'" + "," + "'" + sexe + "'" + "," + "'" + id + "'" + "," + "'" + adresse + "'");
            System.out.println(i);

            try {
                liste = co.requete("nom", "patient", "");
            } catch (SQLException ex) {
                Logger.getLogger(SecretaireMedicale.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println(liste.toString());
            JOptionPane.showMessageDialog(this, "Patient ajouté", "Confirmation", JOptionPane.INFORMATION_MESSAGE);

            try {
                co.deconnexion();
            } catch (Exception ex) {
                Logger.getLogger(SecretaireMedicale.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_jButton3MouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5MouseClicked

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed

    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        random r = new random();
        ConnexionBD co = new ConnexionBD();
        ArrayList<ArrayList<String>> listeId = new ArrayList<>();
        String id = r.genererId(10);
        try {
            co.connexion();
        } catch (Exception ex) {
            Logger.getLogger(ConnexionSIR.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            listeId = co.requete("idpatient", "patient", "");
            System.out.println(listeId.toString());

        } catch (SQLException ex) {
            Logger.getLogger(SecretaireMedicale.class.getName()).log(Level.SEVERE, null, ex);
        }
        while (listeId.get(0).contains(id)) {
            id = r.genererId(10);
        }
        jTextField3.setText(id);
        try {
            co.deconnexion();
        } catch (Exception ex) {
            Logger.getLogger(SecretaireMedicale.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            ConnexionBD co = new ConnexionBD();
            DefaultListModel model = new DefaultListModel();
            ArrayList<String> listNom = new ArrayList<>();
            ArrayList<String> listPrenom = new ArrayList<>();
            ArrayList<ArrayList<String>> listepatient = new ArrayList<>();

            ListeExamenBD listeE = new ListeExamenBD();

            ListePatientBD listeP = new ListePatientBD(listeE.getListeExamen());

//        try {
//            co.connexion();
//        } catch (Exception ex) {
//            Logger.getLogger(ConnexionSIR.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        try {
//
//            listepatient = co.requete("nom,prenom,idpatient", "patient", "");
//
//        } catch (SQLException ex) {
//            Logger.getLogger(SecretaireMedicale.class.getName()).log(Level.SEVERE, null, ex);
//
//        }
            for (int i = 0; i < listeP.getListePatient().size(); i++) {
                model.addElement(listeP.getListePatient().get(i).getId() + "   " + listeP.getListePatient().get(i).getNom() + "   " + listeP.getListePatient().get(i).getPrenom());
                //  model.addElement(listepatient.get(2).get(i) + "  " + listepatient.get(0).get(i) + "  " + listepatient.get(1).get(i));
            }
            jList1.setModel(model);

        } catch (Exception ex) {
            Logger.getLogger(SecretaireMedicale.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_formWindowOpened

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        if (jList1.isSelectionEmpty() == false) {
              
         Patient p= new Patient();
         
            try {
              
                String IdNomPrenom = jList1.getSelectedValue().toString();
                String nom = IdNomPrenom.split("   ")[1];
                String prenom = IdNomPrenom.split("   ")[2];
                String Id = IdNomPrenom.split("   ")[0];
  
                ListeExamenBD listeE = new ListeExamenBD();
                ListePatientBD listeP = new ListePatientBD(listeE.getListeExamen());
               
                for (int i = 0; i < listeP.getListePatient().size(); i++) {
                    if (listeP.getListePatient().get(i).getId().equals(Id)) {
                        p.setDateN(listeP.getListePatient().get(i).getDateN());
                        p.setId(Id);
                        p.setListeExam(listeE.getListeExamen());
                        p.setNom(nom);
                        p.setPrenom(prenom);
                        p.setSexe(listeP.getListePatient().get(i).getSexe());
                      
                    }
                  
                }
                String AffichageLE="";
                
                for(int i=0;i<p.getListeExam().size();i++){
                     AffichageLE+= "\n Type Examen :"+p.getListeExam().get(i).getTypeExamen().toString()+"\n"+"Date :"+p.getListeExam().get(i).getDate()+"\n"+"Praticien :"+"blabla"+"\n"+"Compte Rendu"+p.getListeExam().get(i).getCr();
                }
               
                this.jTextArea1.setText("Nom :" + nom + "\n" + "Prénom" + prenom + "\n" + "Date de Naissance :" + p.getDateN().toString()+"\n"+"Sexe :"+p.getSexe().toString()+"\n"+"Examens : \n"+AffichageLE);
                
            } catch (Exception ex) {
                Logger.getLogger(SecretaireMedicale.class.getName()).log(Level.SEVERE, null, ex);
            }
            

        }

    }//GEN-LAST:event_jList1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecretaireMedicale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecretaireMedicale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecretaireMedicale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecretaireMedicale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SecretaireMedicale().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(SecretaireMedicale.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(SecretaireMedicale.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
